src/style/app.css

- gendo 연동을 위한 제어 UI 개선
- APIServer, ControlServer, PnPDaemon 배포
- aos 제어 화면 확인 -> 가운데정렬, 검은 배경

DEV-12104 gendo 연동을 위한 제어 UI 개선

---

src/app/googDevice/client/StreamClientScrcpy.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/style/app.css

- 데모데이 피드백 일부 반영:
- 버튼 크기 줄이기, 텍스트 크기
- Android 키보드 타이핑 기본 활성화

DEV-12344 [Ramiel] 2021-7-1 데모데이 피드백 반영

---

README.md
src/server/services/HttpServer.ts

DEV-11721 apply hmac signature based authentication

---

src/app/googDevice/client/StreamClientScrcpy.ts
src/app/index.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts

- 테스트 시작 시 앱 키로 실행 기능 추가
- 테스트 종료 시 앱 키로 종료 및 화면 잠금

DEV-12386 [Ramiel] android 앱 키로 실행/종료 기능 (7/1 데모데이 피드백)

---

.gitignore
README.md
package-lock.json
package.json
settings_local_sample.json
src/app/client/StreamReceiver.ts
src/app/googDevice/client/StreamClientScrcpy.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/server/Config.ts
src/server/Utils.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts
src/style/app.css
src/types/Configuration.d.ts

DEV-12387 [Ramiel] 동시 접속 수 제한 (7/1 데모데이 피드백)

---

.github/pull_request_template.md
README.md
_provisioning/00.install.sh
_provisioning/01.run.sh
_provisioning/50.cleanup.sh
_provisioning/99.uninstall.sh
_provisioning/configuration/etc/launchd/ramiel.ws-scrcpy.hbsmith.io.plist
_provisioning/env.sh
src/style/app.css

- 폰트, 배경색 수정
- 독립적인 설치 스크립트 추가

DEV-12424 [Ramiel] 피드백 반영 및 오류 수정

---

_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local_sample.json
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

DEV-12826 integrate with sachiel

---

README.md
_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local_sample.json
src/server/Config.ts
src/server/Utils.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts

- replace aes key with an alternative를 위한 추가 ㅖㄲ

DEV-12826 ramiel api를 sachiel 에 통합

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 안드로이드 장비가 속도측정에서 발생한 오류를 위한 조치
- 로그 보강
- 장비 해제 시도 2회 -> 3회로 증가

DEV-13214 [Ramiel] 안드로이드 장비가 속도측정에서 spike 발생

---

_provisioning/configuration/etc/launchd/ramiel.ws-scrcpy.hbsmith.io.plist

QA Merge W44/45/46

---

src/server/Utils.ts

- API 호출 시 401 error 해결
- 참조: https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#Case2:-%EC%84%B8%EC%85%98-%EC%83%9D%EC%84%B1-%EC%8B%A4%ED%8C%A8
- 다음 PR 참조: https://github.com/HardBoiledSmith/ramiel/pull/111

DEV-13468 [ramiel] OP 환경에서 세션 이슈 재발

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- adb로 keyevent 와 앱 실행 명령어 전송이 의도한 순서대로 동작하지 않음
- Promise 문법을 적용하여 순서를 보장한다

DEV-13493  [Ramiel] 간헐적으로 앱 실행이 되지 않는 이슈

---

_provisioning/01.run-ios.sh
_provisioning/configuration/etc/launchd/ramiel.ws-scrcpy-ios.hbsmith.io.plist

- ws-scrcpy의 iOS 기능 활성화
- 참조: https://github.com/HardBoiledSmith/ramiel/pull/140

DEV-13564 [라미엘] ws-scrcpy의 ios 지원 기능 검토 2022 1Q

---

_provisioning/01.run-ios.sh
_provisioning/configuration/etc/launchd/ramiel.ws-scrcpy-ios.hbsmith.io.plist
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts

QA Merge: 2022 W4/5/6 1st 

---

src/server/Utils.ts
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 앱이 간헐적으로 실행되지 않는 증상 해결
- 정확히는 타이밍 이슈로 이전 세션에 의해, 현 세션에서 실행된 앱이 종료되어 버리는 현상임
- 상세 분석: https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#Type-1:-%EC%95%B1%EC%9D%B4-%EC%8B%A4%ED%96%89%EB%90%98%EC%A7%80-%EC%95%8A%EC%9D%8C
- 타 이슈와 예후 추적을 위한 로깅 보강
- 재현이 어려워 운영 환경에서 재발 여부를 추적해야 함
- https://hbsmith.atlassian.net/browse/DEV-14465

DEV-14465 [라미엘] 블랙스크린 or 빈 화면 Type1 - 앱이 간헐적으로 실행되지 않음

---

src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 빈 화면, 앱 꺼집 현상 이슈에 대한 잠재적인 이슈 방지
- 비동기 함수
- 누락된 user-agent 표시 기능 복원
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

[라미엘] 빈 화면 or 앱 꺼짐 현상 이슈 해결 Cont

---

_provisioning/01.run-ios.sh
_provisioning/01.run.sh

- nvm으로 설치한 node를 사용하도록 실행 시 환경변수 추가
- ramiel PR참조: https://github.com/HardBoiledSmith/ramiel/pull/200

DEV-15166 [라미엘] retries=3시에도 실패. homebrew로 node 설치 시 종종 발생

---

src/server/Utils.ts
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/mw/MjpegProxyFactory.ts

QA Merge: W26/27/28 1st

---

src/app/Util.ts
src/app/client/ManagerClient.ts

- iphone, android 서비스에서 회색화면 (ERR_CONNECTION_RESET) 대비 3회 재시도 기능 추가
- 로컬 환경에서 재현이 대단히 어려움
- OP, 특히 0082 맥미니에서 비교적 높은 빈도로 발생함
- 0082 맥미니 연결 장비, 특히 wclub 아이폰13에서 재발 여부 확인
- 1주 이상 추적 관찰 후 WIP 해제 여부 판단

DEV-15737 [라미엘] 회색화면 (ERR_CONNECTION_RESET) 대비 3회 재시도 기능 추가

---

src/app/client/ManagerClient.ts

- 이슈 해결: 안드로이드 접속 시 상시 사용 중 세션
- 안드로이드, iOS 접속 성공

DEV-15938 [라미엘] 안드로이드 접속 시 상시 사용 중 세션

---

src/app/applDevice/KeyInputHandler.ts
src/app/applDevice/client/StreamClient.ts
src/app/applDevice/client/StreamClientMJPEG.ts
src/app/applDevice/client/WdaProxyClient.ts
src/app/client/StreamReceiver.ts
src/app/controlMessage/ControlMessage.ts
src/app/googDevice/KeyInputHandler.ts
src/app/googDevice/client/StreamClientScrcpy.ts
src/app/index.ts
src/app/player/MsePlayer.ts
src/server/Config.ts
src/server/Utils.ts
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/mw/MjpegProxyFactory.ts
src/server/services/HttpServer.ts
src/style/app.css
src/types/MessageRunWdaResponse.ts

- 포트 할당 시 file lock 메커니즘 개선
- 포트 할당이 필요한 액션에서 2회 재시도 추가
- 1차 시도: 기본 할당 범위로 포트 할당 시도
- 2차 시도: filelock 현황 파악 후, 마지막 포트 + 1번 ~ 40000 범위로 변경하여 다시 할당 시도
- 라미엘 iOS 배포
```bash
BRANCH_WS_SCRCPY=DEV-15930 ./provisioning.py on-premise
```
- 정상 접속 확인
- 예) http://localhost:28100/?app_key=com.lotte.smartwish&user-agent=HELLO_WORL22222222D#!action=stream-mjpeg&player=mjpeghttp&udid=00008020-00094C693A33002E

DEV-15930 [라미엘] W30/31/32 이슈 대응 - 연결 끊어짐, 렉 이슈 우선

---

src/server/services/HttpServer.ts

- nginx timeout에 맞추어 node.js 타임아웃 연장
- OP에서 502 bad gateway 현상이 없어져야 함

DEV-16530 [ramiel] 502 bad gateway 발생

---

src/app/applDevice/client/StreamClient.ts
src/app/applDevice/client/StreamClientMJPEG.ts
src/app/client/StreamReceiver.ts
src/app/googDevice/client/StreamClientScrcpy.ts
src/app/googDevice/filePush/FilePushHandler.ts
src/app/googDevice/filePush/FilePushStream.ts
src/app/index.ts
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 연결되지 않은 iOS 연결 시도 시 서버 크래시 이슈 해결
- 상기 원인 재발 방지를 위한 전수 검사 실시
- 전수 검사 중 발견된 lint, warning 해결
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-16510 ./provisioning.py on-premise`
- iOS, android 동작 정상 확인

DEV-16510 [라미엘] 없는 iOS 장비 접속 시도 시 서버 크래시

---

src/app/Util.ts
src/app/client/ManagerClient.ts

- 웹소켓 연결 3회 재시도 루틴 철회
- 참조) https://github.com/HardBoiledSmith/ws-scrcpy/pull/98
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-16345 ./provisioning.py on-premise`
- iOS, android 접속 확인

DEV-16345 [라미엘] 롤백: bundle.js다운로드 성공 후 ws 연결 실패 & 3회 재시도 모두 실패

---

_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local.json
_provisioning/configuration/etc/ramiel/ws-scrcpy/settings_local_sample.json
package.json
src/server/Config.ts
src/server/Utils.ts
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts
src/types/Configuration.d.ts

- sentry.io 연동
- 배포 `BRANCH_WS_SCRCPY=DEV-14886 ./provisioning.py on-premise`
- 임의의 폰 연결
- 연결 끊어짐, 사용 중 장비 등의 사례 재현
- 브라우저 sentry.io --> Releases --> sample_ramiel 중 가장 최근 --> 메시지 확인
- https://sentry.io/organizations/hbsmith-inc/releases/?project=4504053395292160
- Discovery --> Saved Queries --> sampleRamielEvents
- https://sentry.io/organizations/hbsmith-inc/discover/results/?id=16937&project=4504053395292160&statsPeriod=7d
- Issues
- discovery

DEV-14886 [라미엘] sentry.io 연동

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

SA-1300 [라미엘][운영팀:개발팀] 테스트 조건이 동일한 경우, 스크롤 범위 고정 요청(롤백)

---

src/app/applDevice/client/WdaProxyClient.ts
src/app/applDevice/toolbox/QVHackToolBox2.ts

- 라미엘(iOS) 스크롤버튼 기능 추가
- 라미엘 dev 배포: ./provisioning.py dev
- ws-scrcpy 배포: npm run dist:dev && node dist/index.js
- 왼쪽 상단 스크롤 버튼 동작 확인

SA-1588 [운영팀: SA팀] 라미엘(iOS) 스크롤 기능 개발 가능여부 검토 요청 

---

src/app/controlMessage/ControlMessage.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 라미엘 Android 앱 종료 기능 추가
- 라미엘 dev 배포: ./provisioning.py dev
- ws-scrcpy 배포: npm run dist:dev && node dist/index.js
- 왼쪽 상단 앱종료 버튼 동작 확인

SA-1283 [라미엘] iOS와 Android 기능 동기화

---

src/app/applDevice/client/WdaProxyClient.ts

- 라미엘 iOS 스크롤 범위 수정
- 라미엘 dev 배포: ./provisioning.py dev
- ws-scrcpy 배포: npm run dist:dev && node dist/index.js
- 왼쪽 상단 스크롤 버튼 동작 확인

SA-1649 라미엘 iOS 스크롤 범위 수정

---

src/app/applDevice/client/WdaProxyClient.ts
src/app/applDevice/toolbox/QVHackToolBox2.ts
src/app/controlMessage/ControlMessage.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

QA Merge: W14/15/16 1st

---

src/app/applDevice/client/WdaProxyClient.ts
src/app/interactionHandler/SimpleInteractionHandler.ts
src/common/ControlCenterCommand.ts
src/common/WDAMethod.ts
src/server/Utils.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts
typings/appium-xcuitest-driver/build/lib/driver.d.ts

- Tap Hold + DragFromToWithDuration 기능으로 앱 이동 기능 구현
- Tap Hold: 0.5초 이상 이동 없이 클릭을 유지하면 발동
- DragFromToWithDuration: 터치 후 0.5 이상 유지 후, 터치를 유지한 상태로 이동 후 떼면 발동
- 배포: `BRANCH_WS_SCRCPY=DEV-18358 ./provisioning.py on-premise`
- 브라우저 --> 아이폰 연결 --> 화면 빈 곳 Tap Hold --> 앱 관리가 활성화 되는지 확인
- 임의의 앱 아이콘에 DragFromToWithDuration 을 수행하여 맨 뒤로 보내지는지 확인 - 영상 첨부
https://github.com/HardBoiledSmith/ws-scrcpy/assets/12525941/cf3206df-98ff-4a54-a4c2-36c09bdac8d7

DEV-18358 [라미엘] iOS에 Long Press 기능 추가

---

src/server/services/HttpServer.ts

- 장비 별 팀 할당 멀티 지정 가능
- 참조
- https://github.com/HardBoiledSmith/sachiel/pull/1358
- https://github.com/HardBoiledSmith/naoko/pull/815
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/152
- https://github.com/HardBoiledSmith/nerv/pull/661
- https://github.com/HardBoiledSmith/hbsmith-database/pull/439
- naoko 에서 통합 테스트 진행: https://github.com/HardBoiledSmith/naoko/pull/815

DEV-18710 [라미엘] 장비 별 팀 할당 멀티 지정 가능

---

src/server/Utils.ts
src/server/services/HttpServer.ts

QA Merge: W24/25/26 2nd

---

src/server/services/HttpServer.ts

QA Merge: W24/25/26 3rd

---

src/server/appl-device/services/WDARunner.ts

- 아이폰 이벤트 발생 시 로깅
- 다음 이슈 추적을 위함: https://hbsmith-inc.sentry.io/issues/4237602434/events/0e12ec92d378422c8bad1c5effa3b387/?project=4504053395292160&referrer=previous-event
- `UnknownError: An unknown server-side error occurred while processing the command. Original error: Invalid parameter not satisfying: point.x != INFINITY && point.y != INFINITY`
- OP에서 로깅확인

DEV-18651 [라미엘] 좌표 클릭 이상

---

src/server/appl-device/services/WDARunner.ts
src/server/services/HttpServer.ts

QA Merge: W27/28/29 1st

---

src/server/services/HttpServer.ts

- echo api 추가
- 참조
- [johanna](https://github.com/HardBoiledSmith/johanna/pull/721)
- [magi](https://github.com/HardBoiledSmith/magi/pull/1092)
- [ws-scrcpy](https://github.com/HardBoiledSmith/ws-scrcpy/pull/159)
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-18625 ./provisioning.py on-premise`
- echo 확인: `curl localhost:28500/echo -v` --> 200 OK

DEV-18625 [라미엘] 응답없는 맥미니 cloudwatch - pagerduty 알람 모니터링 추가

---

src/server/appl-device/services/WDARunner.ts
src/server/services/HttpServer.ts

QA Merge: W27/28/29 2nd

---

package.json
src/server/services/HttpServer.ts

DEV-18871 ws-scrcpy sentry 패키지 깨짐

---

package.json
src/server/services/HttpServer.ts

QA Merge: W27/28/29 3rd

---

package.json
src/server/appl-device/services/WDARunner.ts
src/server/services/HttpServer.ts

OP Merge: W27/28/29 2nd

---

src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts

- 상세 불명의 로깅 발생
- api server 통신 부분에 대한 로깅 보강
- 표준 axois 에러 핸들링 적용
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-18522 ./provisioning.py on-premise`
- 같은 아이폰, 안드로이드 장비에 세션 2개씩 연결
- 사용 중 장비 메시지 확인
- 로그에서 에러 로깅 확인
additional data 추가

DEV-18522 [라미엘] Error: connect ETIMEDOUT 15.165.135.134:443

---

src/server/appl-device/mw/WebDriverAgentProxy.ts

DEV-19023 [라마엘] QA hotfix 20230802

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- test apk 배포 지원
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-18840 ./provisioning.py on-premise`
- 세션 열기
- 다음 두 apk 드래그 앤 드랍 후 정상 설치 확인
- jira 링크 참조: https://hbsmith.atlassian.net/browse/DEV-18840?focusedCommentId=137895

DEV-18840 [라미엘] 드래그드롭 apk 설치실패시 -t 옵션으로 설치 재시도

---

src/app/controlMessage/CommandControlMessage.ts
src/app/controlMessage/ControlMessage.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/mw/WebsocketProxy.ts

QA Merge: W39/40/41/42 2nd

---

src/server/Utils.ts

- 파일락이 잡힌 상태에서, 다음 파일을 찾지 못하고 있음
- 해당 버그 수정
- 특히 OP 0078 맥미니에서 장비 연결이 되지 않는 현상 개선

DEV-19492 [라미엘] 0078 맥미니에서 파일락 이슈 다발: 0140,0038

---

src/server/appl-device/services/WDARunner.ts

- `TypeError: i.stack.include is not a function` 이슈 해결
- OP에서 다음 오류 잡히지 않음: `DEV-19631 TypeError: i.stack.include is not a function`
- 빈도: 30일 중 50여회

DEV-19631 TypeError: i.stack.include is not a function

---

src/app/controlMessage/CommandControlMessage.ts
src/app/controlMessage/ControlMessage.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- adb keyboard를 이용한 범용적인 sendText 구현
- 침조
- https://github.com/HardBoiledSmith/ramiel/pull/481
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/199
- 라미엘 PR에서 통합 테스트 진행: https://github.com/HardBoiledSmith/ramiel/pull/481

DEV-19351 [라미엘] 안드로이드 sendtext 문제해결시도 #2

---

src/app/controlMessage/CommandControlMessage.ts
src/app/controlMessage/ControlMessage.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/common/ControlCenterCommand.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/server/services/HttpServer.ts

DEV-20301 [라미엘] sendtext v2 선 반영 - op 롤백

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 갤럭시 s7에서 ime reset 미지원 이슈 해결

DEV-20311 [라미엘] 구버전에서 ime reset 미지원 이슈

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

QA Merge: 2024 W4/5/6 3rd

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 구버전/신버전 안드로이드에서 ime 이슈 해결
- qa에서 fold2, s7 모두 sendtext 작동 정상
- 2회 이상 시도 모두 성공

DEV-20311 [라미엘] 구버전에서 ime reset 미지원 이슈 #3

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

QA Merge: 2024 W4/5/6 4th

---

src/server/services/HttpServer.ts

- ip가 있는 장비는 연결 거부
- 참조
- https://github.com/HardBoiledSmith/ramiel/pull/527
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/214
- https://github.com/HardBoiledSmith/nerv/pull/749
- https://github.com/HardBoiledSmith/hbsmith-database/pull/501
- https://github.com/HardBoiledSmith/sachiel/pull/1560
- v2 장비 연결 시도 시 406 에러 발생

DEV-20753 [라미엘] v2 기능 구현 #6

---

src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- bardiel 사용
- 참조
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/217
- https://github.com/HardBoiledSmith/bardiel-android/pull/1
- https://github.com/HardBoiledSmith/ramiel/pull/583
- https://github.com/HardBoiledSmith/ramiel/pull/583 참조햐여 테스트 진행

DEV-21431 [라미엘] Bardiel v2: AdbKeyboard 기반 전용 키보드앱 개발 #1

---

src/app/applDevice/client/StreamClient.ts
src/app/applDevice/client/WdaProxyClient.ts
src/app/applDevice/toolbox/QVHackToolBox2.ts
src/app/googDevice/client/StreamClientScrcpy.ts
src/app/googDevice/toolbox/DroidToolBox2.ts
src/public/index.html
src/server/appl-device/mw/WebDriverAgentProxy.ts
src/server/appl-device/services/WDARunner.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts
src/types/MessageRunWdaResponse.ts

- isScrolling, isReadyToUse 지원
- 참조
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/218
- https://github.com/HardBoiledSmith/gendo/pull/1806
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/218
- https://github.com/HardBoiledSmith/ramiel/pull/586
- 참조) https://github.com/HardBoiledSmith/naoko/pull/977

DEV-21037 [데이터팀: 개발팀] 라미엘 스크롤 이동이 종료되지 않은 상태에서 다음 스텝의 (탐지후)클릭이 동작하는 현상 수정 요청

---

src/app/googDevice/client/StreamClientScrcpy.ts
src/app/interactionHandler/InteractionHandler.ts
src/server/goog-device/mw/WebsocketProxyOverAdb.ts

- 안드로이드 이벤트 결과 뿌려주기
- 클릭 좌표 화면에 찍어주기
- 라미엘1 배포
- 클릭 좌표 확인
https://github.com/user-attachments/assets/5c8e6181-1673-4248-8bf6-14ea62956019

DEV-22392 [라미엘1] 안드로이드 이벤트 결과 뿌려주기
