src/app/googDevice/WindowsKeyCodeToKey.ts
- fix win32 key mapping and javascript key value code for `-`
=> DEV-13492 [Ramiel] 2021-11-24 키보드 이슈

src/server/services/HttpServer.ts
- HMAC timeout을 300 초로 연장
- 시간측정 시작 (기준 시각)
- naoko -> 리얼디바이스 접속 -> 브라우저의 redirect url 복사 -> 브라우저 창 닫기
- 기준 시각으로부터 250초 경과 -> 브라우저에서 복사해둔 redirect url로 재접속 -> 접속 성공
- 기준 시각으로부터 330초 경과 -> 브라우저에서 복사해둔 redirect url로 재접속 -> timestamp 문구 출력 후 접속 실패
=> DEV-13556 HMAC timeout을 300 초로 연장

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 이미 사용중인 장비일 경우, 누가 사용중인지 표시 (userAgent)
- vagrant up
- master: db, sachiel, nerv, gendo, ramiel
- 리얼 디바이스를 ramiel vagrant에 연결
- nerv에서 새로 연결한 리얼디바이스에 hbsmith 팀 할당: nerv -> Real Devices -> attach ...
- ws-scrcpy 동기화
- ramiel vagrant 접속
- cd /opt/ramiel/ws-scrcpy
- .git/config 수정 -> master -> *
- `git fetch -a; git checkout DEV-13718`
- ws-scrcpy 서비스 재시작: `launchctl stop ramiel.ws-scrcpy.hbsmith.io`
- 이미 사용중인 세션의 userAgent 확인 (naoko)
- gendo -> naoko 실행 -> 플랫폼에서 연결한 리얼다비이스 선택 -> 녹화 시작 -> 크롬에서 장비 세션 연결까지 대기 -> 연결 후 주소복사 -> 새 탭 열어 붙여넣고 열기 -> 문구 확인 (아래 스크린샷 확인) -> 녹화 종료
- 이미 사용중인 세션의 userAgent 확인 (gendo)
- gendo -> gendo.sln을 visual studio로 열기 -> 위 단계에서 만든 녹화본 경로 사용하여 gendo 실행 -> 크롬에서 장비 세션 연결까지 대기 -> 연결 후 주소복사 -> 새 탭 열어 붙여넣고 열기 -> 문구 확인 (아래 스크린샷 확인)
- 정상적인 연결
- 이미 사용중인 장비 (naoko)
- 이미 사용중인 …
=> DEV-13718 [라미엘] 세션 잠금 상태 메시지에 user-agent 표시

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 테스트 시작/끝 시점에서 모든 앱 강제종료
- 대상 앱: 화면이 있는 것들
- vagrant up
- master: db, sachiel, nerv, gendo, ramiel
- 리얼 디바이스를 ramiel vagrant에 연결
- nerv에서 새로 연결한 리얼디바이스에 hbsmith 팀 할당: nerv -> Real Devices -> attach ...
- ws-scrcpy 동기화
- ramiel vagrant 접속
- cd /opt/ramiel/ws-scrcpy
- .git/config 수정 -> master -> *
- `git fetch -a; git checkout DEV-13718`
- ws-scrcpy 서비스 재시작: `launchctl stop ramiel.ws-scrcpy.hbsmith.io`
- 리얼 디바이스에서 임의의 앱을 수동으로 실행
- gendo -> naoko 실행 -> 플랫폼에 리얼 디바이스 선택 -> 앱키에 `com.lotte` (롯데 앱이 설치되어 있어야 함) -> 세션 연결
- 수동으로 실행한 앱이 종료되고, 앱키로 설정한 앱이 실행되는지 확인
- 참고 영상
https://user-images.githubusercontent.com/12525941/148327890-37d55776-51f2-4e82-b6c1-04e24704b642.mov
=> DEV-13561 [라미엘] 테스트 시작/끝 모든앱 강제종료

src/app/applDevice/client/WdaProxyClient.ts, src/server/appl-device/services/WDARunner.ts, typings/appium-xcuitest-driver/build/lib/driver.d.ts
- 세션 시작 또는 종료 시 활성화된 앱이 있으면 종료시킴
- 한계: 모든 앱 종료는 구현이 어려움
- vagrant up:
- master: sachiel, db
- 라미엘 배포
```bash
cd <...>/ramiel
git checkout master
export BRANCH_WS_SCRCPY=DEV-14481
./provisioning.py on-premise
```
- 아이폰 연결
- 수동으로 폰에 앱을 띄움
- 앱키가 없이 세션 시작 -> 앱이 종료된 상태로 뜨는지 세션이 뜨는지 확인
- 임의의 앱을 실행한 상태에서 세션 종료
- 다시 세션 연결 -> 앱이 종료된 상태로 뜨는지 세션이 뜨는지 확인
https://user-images.githubusercontent.com/12525941/159840553-861da65e-d243-48b4-b437-0bd3408b4722.mov
=> DEV-14481 [라미엘] iOS 자동종료 기능 - 앱키 미기재 시, 안드로이드와 달리 앱 자동종료되지 않음

src/server/appl-device/mw/WebDriverAgentProxy.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 장비 연결이 끊어져 있거나 점검 중일 경우 410 GONE 리턴
- 기존 503 에러는 서버 크래시에 사용하는 것이 컨텍스트에 맞음
- 참조)
- https://github.com/HardBoiledSmith/sachiel/pull/1099
- https://github.com/HardBoiledSmith/ws-scrcpy/pulls
- db master vagrant up
- sachiel: `BRANCH=DEV-14479 vagrant up`
- 모든 유닛테스트 통과
=> DEV-14479 sachiel: POST /real-devices/<device_id>/control/에서 exception 발생

src/app/applDevice/client/StreamClientMJPEG.ts, src/app/applDevice/client/WdaProxyClient.ts, src/common/WDAMethod.ts, src/server/Utils.ts, src/server/appl-device/services/WDARunner.ts
- 다음의 이슈 해결 또는 완화:
- WDA가 정상이나 ws-scrcpy로 iOS 세션 연결 시 갑자기 끊어짐 [경과 확인 중]
- iOS 세션에서 연속으로 입력 시 WDA 프로세스가 죽음 [경과 확인 중]
- iOS에 많은 입력 → WDA에서 처리하는 속도가 따라가지 못함. 간간히 롯데ON 앱 크래시 [경과 확인 중]
- WDA 크래시 [경과 확인 중]
- 입력이 많이 남은 상태에서 세션 종료 → 남은 명령과 TearDown 프로세스가 꼬임 → 다음 테스트에 영향 [경과 확인 중]
- 참조) https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#2022-5-16-WebDriverAgent-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EA%B0%80-%EC%A3%BD%EA%B1%B0%EB%82%98-%EC%B2%98%EB%A6%AC-%EC%86%8D%EB%8F%84%EA%B0%80-%EB%96%A8%EC%96%B4%EC%A7%90
프로비저닝 프로필에 등록된 iOS가 필요하여 선택사항임.
- master vagrant up: db, sachiel
- `BRANCH_WS_SCRCPY=DEV-14939 ./provisioning on-premise`
- iOS 세션 접속
- 세션 접속 -> 롯데ON 앱 열기 -> 이전 대비 반응 속도 향상 확인
- 세션 접속 -> 롯데ON 앱 열기 -> 0.5초 미만 간격을 빠르게 30회 카테고리 항목을 터치 -> WDA가 죽지 않는 것 확인. (50회 반복 시 죽음)
=> DEV-14939 [라미엘] WDA가 죽는 현상

build.config.override.json
- 잘못 커밋된 iOS 설정 롤백
- `build.config.override.json` 파일은 이미 커밋이 되어 있기에, `.gitignore`에 추가하는 것은 의미가 없음
- 여러 방법을 고민하였으나, 원격에서 파일을 유지하면서 로컬에서만 커밋을 무시하는 간단한 방법은 딱히 없음
- 참조) https://cppmaster.tistory.com/entry/Git%EC%97%90-tracking%EC%A4%91%EC%9D%B8-file%EC%9D%84-ignore-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
1. 원격에서 삭제하고 로컬에서 .gitignore에 추가
1. `git update-index --assume-unchanged [path]` -> clone 할 때마다 적용 필요
1. `git update-index --skip-worktree [path]`  -> clone 할 때마다 적용 필요
- 대안 1~3이 적용이 복잡하거나 클론할 때마다 명령어를 실행해야 한다. 따라서 내용을 삭제하고 현행을 유지하기로 하였음
=> DEV-15125 build.config.override.json에서 iOS 설정 롤백

src/server/appl-device/services/WDARunner.ts
- 튜닝값 롤백: `waitForQuiescence`
- 사유
- 앱 시작 기능이 잘 동작하지 않음
- 시간 경과 후 WDA 반응 속도가 매우 떨어짐
- OP 영향을 최소화 하기 위해 아래의 절차를 제안함
- 대상: iOS 서비스가 활성화된 맥미니만
- 절차: OP merge -> 수동으로 ws-scrcpy-ios만 업데이트 후 재시작:
```bash
cd /opt/ramiel/ws-scrcpy-ios; git pull
kill -9 $(ps -ef |grep xcodebuild |grep -v grep| awk '{print $2}')
launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io
```
=> DEV-15167 [라미엘] iOS 속도 저하 현상 해결을 위한 핫픽스

package-lock.json, src/app/applDevice/client/StreamClient.ts, src/common/WdaStatus.ts, src/server/appl-device/services/WDARunner.ts
- 이슈 상세: https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#2022-5-30-iOS-%ED%81%B4%EB%A6%AD%EB%A8%B9%ED%86%B5%EA%B3%BC-%ED%94%84%EB%A6%AC%EC%A7%95-%EC%9D%B4%EC%8A%88
- wdaEvent Queue 관련 초기화 버그 수정
- ~세션 시작 시, 앱 키로 종료하는 기능 폐지~
- 정정: 세션 시작 시, 주어진 앱 키가 있다면 해당 앱키로 앱을 활성화 시켰다가 종료시킴
- 사유: 10분 이상 백그라운드에 있는 앱을 종료하려 시도할 경우 1분의 타임아웃이 걸리기 때문 (XCUITest 버그)
- 제어 명령 수행 시 상태 메시지를 보여주고 마우스 아이콘을 WAIT로 변경
- 선택적으로 수행: 프로비저닝 프로필에 등록된 iOS 장비가 있는 경우에만 가능
- sachiel, db master vagrant up
- ramiel 배포:
```bash
export BRANCH=DEV-15202
export BRANCH_WS_SCRCPY=DEV-15202
./provisioning.py on-premise
```
- 10분 텀을 두고 시작 시, 1분 타임아웃이 발생하지 않는지 확인
-수동으로 iOS 조작:
- 롯데온 앱 실행
- 장비 잠금
- 11분 대기 (최소 10분. 넉넉히 1분 더)
- 브라우저를 열고 해당 장비로 세션 접속
- 롯데온 앱 자동 시적 설정
- 예) …
=> DEV-15202 [라미엘] iOS 클릭먹통과 10분 이상 대기 시 terminateApp 1분 멈춤 이슈

src/app/controlMessage/CommandControlMessage.ts, src/app/controlMessage/ControlMessage.ts, src/app/googDevice/filePush/FilePushHandler.ts, src/app/googDevice/filePush/FilePushStream.ts, src/app/googDevice/filePush/ScrcpyFilePushStream.ts, src/app/googDevice/toolbox/DroidToolBox2.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- APK 설치 기능 구현
- Drag & Drop으로 APK 파일 설치 기능은 이미 구현되어 있음
- 원래 APK 설치는 shell로 수행하라고 가이드 되어 있음 -> 자동으로 설치를 트리거하도록 기능 추가
- master up: db, sachiel
- branch up: `BRANCH_WS_SCRCPY=DEV-14082 ./provisioning.py on-premise`
- 인터넷에서 임의의 APK 다운로드
- 안드로이드 폰 연결
- 세션 연결
- 다운받은 APK 파일을 화면에 drag & drop
- 설치 완료 확인
https://user-images.githubusercontent.com/12525941/170008384-87fd0b82-4545-4ea5-a72e-6f427106e4b6.mov
=> DEV-14082 [라미엘] 외부에서 apk 설치 기능

_provisioning/01.run-ios.sh, _provisioning/01.run.sh
- ws-scrcpy가 실행되지 않는 이슈 해결
- nvm installed node보다 brew installed node가 우선하여 선택되어 발생하는 문제
- dv-ramiel에는 node@14와 node latest가 동시에 설치되어 있어, node@14만 지워도 상기 이슈개 발생함
- 동일 이슈 재발을 더 쉽고 간단하게 해결하기 위한 핫픽스를 진행함
=> DEV-15331 [라미엘][Hotfix] ws-scrcpy service가 실행되지 않음

src/server/appl-device/mw/WebDriverAgentProxy.ts, src/server/appl-device/services/WDARunner.ts
- iOS 장비 잠금이 풀리지 않는 이슈 해결
- 세션 초기화/종료 중 WDA down 시 ws-scrcpy가 죽는 문제 해결
- 참조: https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2368929913/Ramiel#20220619-iOS-%EC%9E%A5%EB%B9%84-%EC%9E%A0%EA%B8%88%EC%9D%B4-%ED%92%80%EB%A6%AC%EC%A7%80-%EC%95%8A%EB%8A%94-%ED%98%84%EC%83%81-%EB%8B%A4%EB%B0%9C
- 테스트 가능한 iOS가 있을 경우 선택적으로 수행
- iOS 장비 연결
- 라미엘 배포
```bash
export BRANCH_WS_SCRCPY=DEV-15351
./provisioning.py on-premise
```
- 세션 연결 -> 장비 초기화 중 메시지 확인
- WDA kill : `kill -9 $(ps -ef | grep xcodebuild | grep -v grep | awk '{print $2}')`
- ws-scrcpy가 죽지 않는지 확인
=> DEV-15351 [라미엘] iOS장비 잠금이 해제되지 않음

src/server/mw/MjpegProxyFactory.ts
- MJPEG proxy를 캐싱하지 않도록 함
- iOS 테스트 환경 구성
- 다음 절차를 10회 반복 후, `초기화 완료, 검은 바탕` 증상이 발생하는지 확인:
- iOS에 WDA 실행 확인 -> ws-scrcpy-ios로 세션 접속 확인 -> WDA 강제 종료 -> ws-scrcpy-ios로 세션 접속
- 다음 화면이 노출되지 않아야 함:
=> DEV-15343 [라마엘] 초기화 완료, 검은 바탕

src/server/Utils.ts, src/server/appl-device/mw/WebDriverAgentProxy.ts, src/server/appl-device/services/WDARunner.ts, src/server/mw/MjpegProxyFactory.ts
- 버그 수정: WDA 재시작 시 높은 빈도로 검은화면 발생 후 회복되지 않음
- 해결: holders 로직 폐지. MJPEGProxyFactory에 의한 세션은 holders 감소가 적용되지 않음
- 예외처리 추가: WDA가 죽은 뒤, API 서버에 반영되기 전에 세션 접속 시 서버 크래시
프로비저닝 프로필에 등록된 iOS가 있을 경우 선택적으로 수행
- 환경 구축
- 라미엘 환경 배포
```bash
export BRANCH_WS_SCRCPY=DEV-15491
./provisioning.py on-premise
```
- 아이폰 연결
- 재현
- iOS 세션 연결했다가 종료 후 6초 대기
- wda 프로세스 kill: `kill -9 $(ps -ef | grep xcodebuild | grep -v grep | awk '{print $2}')`
- iOS 세션 다시 연결
- 정상 연결 확인
- ws-scrcpy가 크래시 되지 말아야 함
=> DEV-15491 [라미엘] 초기화 완료, 검은 바탕 #2 - invalid session id로 인해 발생 확인

src/app/applDevice/client/StreamClient.ts, src/app/player/MjpegPlayer.ts, src/common/WdaStatus.ts, src/server/appl-device/services/WDARunner.ts
- 필요성
- iOS 세션 시작 시, 앱키가 주어질 경우, 완벽한 종료를 위해 앱을 강제로 실행 후 종료를 시킴
- gendo에서 때떄로 이 과정을 앱 실행 완료로 인식할 때가 있음
- 이를 방지하기 위한 PR
- setUpTest 중 앱 시작 시점부터 화면을 보여줌
- (OPTIONAL) 장비 Alias 노출 (없을 경우 model)
- 배포: `BRANCH_WS_SCRCPY=DEV-15664 ./provisioning.py on-premise`
- 앱키를 주는 옵션으로 세션 접속:
- 예시) http://localhost:28100/?app_key=com.lotte.smartwish&user-agent=HELLO_WORL22222222D
#!action=stream-mjpeg&player=mjpeghttp&udid=00008020-00094C693A33002E
- 앱 스플래시가 뜨는 시점부터 화면이 켜지는지 확인
https://user-images.githubusercontent.com/12525941/178931996-0a0c37b7-3ed0-459c-858d-36e9f3a36d34.mov
=> DEV-15664 [라미엘] iOS setUpTest 중 앱 시작 시점부터 화면을 보여줌

src/server/appl-device/mw/WebDriverAgentProxy.ts
- 에러 로깅 중복 제거
- 참조)  https://hbsmith.atlassian.net/browse/DEV-16083
- db, sachiel 배포
- 모든 장비 잠금으로 설정
```sql
update hbsmith.hbsmith_real_device set is_occupied=0 where id <> 1;
```
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-16083 ./provisioning.py on-premise`
- 크롬 브라우저 실행
- 개발자 도구 --> console
- iOS 연결
- 로그 확인
- AS-IS:
- 상단 중앙 UI: 알 수 없는 오류라고 나옴
- 로그가 3회 뜸 (중복 로깅으로 인함. 실제 실행 회수는 1회)
- TO-BE
- 상단 중앙 UI: 이미 사용 중인 장비
- 로그 1회
=> DEV-16083 [라미엘] 재시도 사이드 이펙트: 잠김 상태일 때 에러메시지 이상

src/server/appl-device/mw/WebDriverAgentProxy.ts
- 로그 이상 수정
- OP 환경에서 확인 패치 이후 확인
- sentry --> discovery --> saved queries --> udid가 ios 형식이나 ramiel_device_type 값이 Android인 것이 없어야 함
=> DEV-16805 [라미엘] sentry ramiel_device_type 출력 이상

src/server/mw/MjpegProxyFactory.ts
- 이중 wda.release() 동작 제거
- 초기화 실패에 영향을 미치는 이슈는 아니나, 버그는 맞기에 PR 작성
- ramiel 저장소로 배포: `./provisioning.py on-premise`
- ios 장비 접속
- 브라우저로 장비 접속
- xcodebuild 프로세스 kill: `kill -9 $(ps -ef |grep xcodebuild | grep -v grep | awk '{print $2}')`
- filelock 로그가 뜨지 말아야 함
=> DEV-16317 [라미엘] 초기화 실패 이슈- WDA 죽을 때 동작 이상

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 안드로이드 스크롤 범위 오작동 해소
- swipe 명령의 duration 시간을 2초로 늘려 스크롤 민감도 최소화
- 라미엘 dev 배포: `./provisioning.py dev`
- ws-scrcpy 배포: `npm run dist:dev && node dist/index.js`
- 왼쪽 상단 스크롤 버튼 동작 확인
=> SA-1300 [라미엘][운영팀:개발팀] 테스트 조건이 동일한 경우, 스크롤 범위 고정 요청

src/app/applDevice/client/StreamClient.ts, src/app/applDevice/client/WdaProxyClient.ts, src/app/controlMessage/CommandControlMessage.ts, src/app/controlMessage/ControlMessage.ts, src/app/googDevice/client/StreamClientScrcpy.ts, src/common/ControlCenterCommand.ts, src/server/appl-device/mw/WebDriverAgentProxy.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- heartbeat 기능 구현: 클라단 신호가 일정 시간동안 없을 경우 강제로 연결을 종료하는 기능
- 서버단 heartbeat 만료 기간: 2분
- 클라단 heartbeat 갱신 주기: 1분
- db, sachiel master 배포
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-16543 ./provisioning.py on-premise`
- 공통 테스트: iOS/Android 세션 열고 10분 대기 --> 접속 유지 및 제어 정상 확인
- 코드 변조 후 타임아웃 테스트:
- iOS
- `StreamClient.ts` 수정 후 서비스 재시작 `launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io` --> 브라우저로 접속 후 2분 대기
```
this.heartbeatTimer = setInterval(() => {
return this.wdaProxy.sendHeartbeat();
}, 60 * 1000);
```
- Android: `TBD` 수정 후 서비스 재시작 `launchctl stop ramiel.ws-scrcpy.hbsmith.io` --> 브라우저로 접속 후 2분 대기
```
this.heartbeatTimer = setInterval(() => {
// this.sendMessage(CommandControlMessage.createHeartBeatCommand());
}, 60 * 1000);
```
- 타임아웃 발생 후 다른 세션 열 경우 정상 접속 확인
- 타임아웃 발생 후 다른 세션 열 경우 정상 접속 확인
- iOS
- Android
=> DEV-16543 [라미엘] heartbeat 기능 구현

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 안드로이드 스크롤 범위 오작동 해소
- swipe 명령의 duration 시간을 2초로 늘려 스크롤 민감도 최소화
- 라미엘 dev 배포: ./provisioning.py dev
- ws-scrcpy 배포: npm run dist:dev && node dist/index.js
- 왼쪽 상단 스크롤 버튼 동작 확인
=> SA-1396 [라미엘][운영팀:개발팀] 스크롤 범위 고정 요청 복구

src/server/Utils.ts
- 파일락 경로에 서버 포트를 추가
- 목적
- 두 개의 ws-scrcpy 프로세스 (android, ios)가 동일한 파일락 경로 사용 
- 사례) iOS 접속 중 --> ws-scrcpy android 서비스 재시작 --> ws-scrcpy ios의 파일락 초기화 됨 --> iOS 접속에 이슈 발생
- 배포
- sachel, db: master
- ramiel: `BRANCH_WS_SCRCPY=DEV-18306 ./provisioning.py on-premise`
- 다음 환경 설정 후 iOS 정상 연결 확인
1. `/tmp/ramiel_file_lock` 폴더 삭제 --> ws-scrcpy 서비스 재시작 `launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io.plist` --> iOS 정상 접속 확인
1. `/tmp/ramiel_file_lock/28100` 폴더 삭제 --> ws-scrcpy 서비스 재시작 `launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io.plist` --> iOS 정상 접속 확인
1. `/tmp/ramiel_file_lock/28100/*` 모든 파일 --> ws-scrcpy 서비스 재시작 `launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io.plist` --> iOS 정상 접속 확인
=> DEV-18306 [ramiel] Error: ENOENT: no such file or directory, scandir '/tmp/ramiel_file_lock'

src/server/services/HttpServer.ts
- team_name query param 누락으로 QA 환경에서 NotFound가 발생하는 문제 해결시도
=> DEV-18710-1 [라미엘] 장비 별 팀 할당 멀티 지정 가능 (보완 #1)

src/server/Utils.ts
- 파일락 메커니즘 개선:
- /tmp 대신 유저 폴더 사용. /tmp는 비정기적으로 초기화 됨
- 파일락 생성 시 폴더가 있도록 보장함
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-19000 ./provisioning.py on-premise`
- 아이폰, 안드로이드 정상 접속 2회 확인
- `~/.ramiel/` 폴더 확인
=> DEV-19000 [라미엘] 이슈: filelock 폴더`/tmp/ramiel_file_lock`가 간헐적으로 삭제 후 복원되지 않는 이슈가 있음.

src/server/Utils.ts, src/server/appl-device/mw/WebDriverAgentProxy.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts, src/server/services/HttpServer.ts
- ios/android ws-scrcpy 시작 시 각 옵션에 맞는 장비들의 점유 상태 해제
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-18973 ./provisioning.py on-premise`
-  android 테스트: android 접속 (`localhost:28500/...`) --> 장비 연결한 상태에서 서버 재시작: launchctl stop ramiel.ws-scrcpy.hbsmith.io --> 5분 대기 --> 동일 장비 접속 --> 접속 확인
-  iOS 테스트: android 접속 (`localhost:28100/...`) --> 장비 연결한 상태에서 서버 재시작: launchctl stop ramiel.ws-scrcpy-ios.hbsmith.io --> 5분 대기 --> 동일 장비 접속 --> 접속 확인
=> DEV-18973 [라미엘] ws-scrcpy 시작 시 항상 장비를 사용할 수 있는 상태로 전환

src/server/appl-device/services/WDARunner.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 다음 에러 해결:
- case1:  `TypeError: Cannot read properties of undefined (reading 'status')`
- case2: `object null is not iterable (cannot read property Symbol(Symbol.iterator)`
- 원인: 
- case1:
- ts에서 형태: `msg = `[${WdaRunner.TAG}] Cannot retrieve the device ${udid}. resp code: ${error.response.status}`;`
- js에서 형태: `'{snip}  Cannot retrieve the device "+e+". resp code: "+f.response.status:"["+t.TAG+"] "+f.message,console.error(u.Utils.getTimeISOString(),e,p),f;c {snip}`
- concat 형태가 되어 undefined를 이어 붙이게 시도
- case2: 안드로이드 wm size에서 잘못된 값 리턴
- OP sentry에서 `TypeError: Cannot read properties of undefined (reading 'status')` 발생 안 함
=> DEV-18524 [라미엘] TypeError: Cannot read properties of undefined (reading 'status')

src/server/appl-device/mw/WebDriverAgentProxy.ts
- 장비 연결 해제 로직 단순화로 연결 해제 중 발생 가능한 미정의 동작 해결
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-18650 ./provisioning.py on-premise`
- 장비 세션 연결 --> 해제 --> 10초 대기 --> 다시 연결 --> 성공
=> DEV-18650 [라미엘] NoSuchDriverError: Session does not exist

src/server/appl-device/services/WDARunner.ts
- 다음 오류메시지 발생 시 클릭이벤트가 제대로 발생하지 않음: `UnknownError: An unknown server-side error occurred while processing the command. Original error: Invalid parameter not satisfying: point.x != INFINITY && point.y != INFINITY`
- ChatGPT에서 다음 케이스를 제시: 아직 UI 요소가 로딩되지 못했거나 애니메이트 중일 때 발생할 수 있음
- 모든 케이스가 초기화 절차 직후 클릭에서 발생하였음. 이에 상당히 높은 연관이 있어 보임
- 따라서, 해당 에러 메시지 발생 시 3회의 재시도 회수를 주기로 하였음
- OP 0137-I-13-Pro 장비의 lfmall 테스트에서 클릭이 먹히는 증상 완화 (주 3~5회로 추정)
=> DEV-18843 [라미엘] 좌표 클릭 이상 #2 로깅 추적 및 해결방안 모색

src/app/controlMessage/CommandControlMessage.ts, src/app/controlMessage/ControlMessage.ts, src/app/googDevice/toolbox/DroidToolBox2.ts, src/server/goog-device/mw/WebsocketProxyOverAdb.ts, src/server/mw/WebsocketProxy.ts
- [안드로이드 한정] 바르디엘 APK 설치한 경우와 그렇지 않은 경우 모두를 지원하는 코드 추가
-  추가사항
- SetupTest 초기화 과정에서 불필요한 코드실행 방지 및 예외처리 추가 
- 하기 동영상을 참고하여 bardiel apk 를 설치한 경우와 그렇지 않은 경우 모두를 테스트
- 바르디엘이 설치되지 않은 경우 send text 시에 로그에 "bardiel not enabled. use legacy mode." 이 뜨도록 함
설치하지 않은 경우 
https://github.com/HardBoiledSmith/ws-scrcpy/assets/1650254/37562c83-c5b6-4f21-b8f9-dda681474705
설치한 경우
https://github.com/HardBoiledSmith/ws-scrcpy/assets/1650254/7a865130-cbc4-433e-8a41-a7afc5b271da
=> DEV-19182 [라미엘] 안드로이드 sendtext 문제해결시도 #1

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- `Failure: ''` 오류 해결
- sachiel에는 is_connected 상태이나, adb접근 불가일 경우 (대개 재부팅 등으로 인한 타이밍 상 장비 offline)
- 해당 이슈 발생 시 장비가 잠금 상태가 되어 풀리지 않음. 이 문제 역시 해결.
- 라미엘 배포: `BRANCH_WS_SCRCPY=DEV-19630 ./provisioning.py on-premise`
- 안드로이드 폰 연결 --> 세션 연결 성공 확인 --> 연결 해제 --> 물리적 USB 연결 해제 --> nerv에서 is_connected=1 상태로 변경 --> 세션 연결 시도 --> 오류 문구 확인
- sentry에 `Failed: ''` 오류가 남지 않음
=> DEV-19630 FailError: Failure: ''

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 안드로이드14에서 앱닫기 기능 호환성 해결
- 라미엘 배포
- 기능 테스트: 안드로이드14에서 임의의 앱 실행 --> 앱 닫기 버튼 클릭 --> 앱이 닫히는지 확인
- backward compatitability: 안드로이드 13 이하 버전에서 임의의 앱 실행 --> 앱이 닫히는지 확인
=> DEV-20015 [운영팀:개발팀] Cashwalk : 0155 기기 → 라미엘 앱 나가기 버튼 미동작 확인 요청

src/app/applDevice/client/WdaProxyClient.ts, src/app/googDevice/toolbox/DroidToolBox2.ts
- prompt()로 인해 모든 쓰레드 정지됨 --> heartbeat 타암아웃 발생 --> 해당 이슈 해결
- 아이폰, 안드로이드 sendText, reboot, launch/terminateApp 실행 정상
=> DEV-21859 [라미엘] alert창 뜬 상태에서 heartbeat갱신 안 됨

src/server/goog-device/mw/WebsocketProxyOverAdb.ts
- 문자 자동전달앱 서비스 시작 보장 (설치되어 있을 경우만)
- 참조
- https://github.com/HardBoiledSmith/ramiel/pull/611
- https://github.com/HardBoiledSmith/ws-scrcpy/pull/224
- 라미엘1 배포: `BRANCH=DEV=21967 ./provionsing.py on-premise`
- 안드로이드 연결 후 세션 접속
- 문자자동전달앱이 설치되어 있지 않은 경우 --> 정상 접속 성공
- 문자자동전달앱을 설치하는 걍우:
- 원스토어 --> 문자자동전달 --> 설치 --> 설정 스크린샷 참조)
- 세션 해제
- 세션 재접속
- 문자 전송
- 잠시 후 상단 메시지 전송 확인
- 설정: 앱 실행 --> 홈 --> 문자전달
자신의 전번, 이메일주소 사용
- 문자 전송 시
=> DEV-21967 [라미엘1&2] 문자자동전달앱 재시작
